### PR TITLE
New EnableCut and DisableCut Commands

### PR DESCRIPTION
**Pull request by ntaylor-86**
In reference to issue #18 

This pull request will add two additional Commands:
* EnableCut()
* DisableCut()

### CODE REVIEW

**Comment by RamyTalal** [comment]
Thank you for the pull request!

I have one suggestion:

```php
<?php

namespace Talal\LabelPrinter\Command;

class AutoCut implements CommandInterface
{
    /**
     * Brother ESC/P Command Reference
     * 
     * https://download.brother.com/welcome/docp000706/cv_ql720_eng_escp_100.pdf
     * 
     * Advanced commands -> Specify cutting
     * 
     * ASCII:   ESC    i    C    n
     * 
     * Specifies cutting after printing.
     * 
     *     n = 1 or 49 ("1"): Specifies cutting.
     *     n = 0 or 48 ("0"): Cancels cutting.
     * 
     */
    const ENABLED   = 49;
    const DISABLED  = 48;
    
    /**
     * @var int state
     */
    protected $state;

    /**
     * @param int $state
     */
    public function __construct($state)
    {
        $this->state = $state;
    }
     
    /**
     * @inheritdoc
     */
    public function read()
    {
        return chr(27) . 'iC' . chr($this->state);
    }
}
```

Usage:
```php
$printer->addCommand(new Command\AutoCut(Command\AutoCut::ENABLED));
```

What do you think?

**Comment by ntaylor-86** [comment]
Yeah nice! I've added a new commit that does what you suggest.

**Comment by ntaylor-86** [comment]
Cheers @RamyTalal !
I can see that Packagist has already picked up the v1.0.2 tag 👍

**Comment by RamyTalal** [comment]
Thanks again for the PR @ntaylor-86!

**Pull request merged**
