### PR TITLE
Add barcodes feature

### LINKED ISSUE #8: Barcode implementation
I'm working on a (partial, for now) implementation of barcode printing based on your other function implementations,, but it's not actually printing a barcode when I try to use it.  Any chance you could look it over and see what I might be missing?

[BarCode.php.txt](https://github.com/RamyTalal/Label-Printer/files/3203163/BarCode.php.txt)

In my PHP page that prints the label, this is the line I use to write the barcode:
`$printer->addCommand(new Command\BarCode($detailID,48,Command\BarCode::WIDTH_MEDIUM,"code39",false,2.5));`

### PR DESCRIPTION
**Pull request by xelan**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | yes
| Deprecations? | no 
| Tickets       | Fix #8
| License       | MIT

### CODE REVIEW

**Comment by RamyTalal** [comment]
Thank you for your PR! Could reformat Barcode.php so that the style is aligned with the other files?

**Comment by RamyTalal** [comment]
I'm also missing the tests.

**Comment by xelan** [comment]
Sure, I'll update the CS for `Barcode.php` and add some tests :+1: Thanks for the quick feedback and best regards from Austria

**Comment by xelan** [comment]
Hi @RamyTalal! I've added tests, removed unused code (the value objects are currently unused, would be nicer in the future but not needed right now). Also we adapted and tested QR code printing (plus tested them on a Brother QL-580N).

Should I squash the commits before merge or would you prefer to keep the work history as-is?

Thanks and best regards
Andreas

**Comment by RamyTalal** [comment]
Hello @xelan Thanks again for the new changes. What do you mean with the unused value objects?

Squash is fine :)

**Comment by xelan** [comment]
In the first commit of the feature branch for this PR, we had several value objects to encapsulate the constant used in the `Barcode` command class, however they are not used at the moment so I removed them again.

Ok, then I'll squash the commits and give you an update afterwards :+1:

**Comment by xelan** [comment]
Squashed and the updated branch is now pushed :)

**Comment by xelan** [comment]
By the way, the QR code printing, which is marked as TODO in the readme is now implemented (and tested on a QL-580N). If you want, you can also test it and remove it from the TODO if everything works for your label printer as well. And maybe we should add a short readme entry for barcode printing as well?

**Comment by RamyTalal** [comment]
@xelan I've tested the code and it seems to work fine! Can you add the Readme entry? When that's done I can tag a new release. :)

**Comment by xelan** [comment]
Added, thanks :+1:

**Comment by RamyTalal** [comment]
Thanks again for the PR!

**Comment by xelan** [comment]
> Thanks again for the PR!

Thanks for the awesome library and good maintenance! Shouldn't the new version number be bumped to 1.1.0, as it contains new, backwards compatible features?

**Pull request merged**
